FROM postgres:9.5
MAINTAINER docker@unxs.io

#pre-created AdHoc Argentina Odoo 9 DB

COPY ./data /var/lib/postgresql/

# docker build -t unxsio/odoopgarg .
#docker run --restart unless-stopped --environment POSTGRES_USER=odoo --environment POSTGRES_PASSWORD=odoo --name odoopgarg -d unxsio/odoopgarg
